sudo: false
language: ruby
rvm:
  - 2.4.2
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - gem install bundler -v 1.15.3
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
